<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Taja_img-circle</name>
   <tag></tag>
   <elementGuidId>c7c38369-e441-4838-9ca4-2c9836c217d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/nav/div/ul[2]/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f53d4bf9-0fe7-43e3-af74-322b112a770d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://asset.kgnewsroom.com/users/photo-8.jpg</value>
      <webElementGuid>1e200362-b813-42de-b823-1d5b6526d33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user-img</value>
      <webElementGuid>54021798-cdf0-443f-a530-d21623cd74e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>7c8955b4-8b96-44e5-861f-41ebe1392662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>d5039712-d979-40bb-92ed-499648c8acc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/nav[@class=&quot;navbar navbar-default navbar-static-top m-b-0&quot;]/div[@class=&quot;navbar-header&quot;]/ul[@class=&quot;nav navbar-top-links navbar-right pull-right&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle profile-pic&quot;]/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>35b5ca57-bc00-426d-b9fe-d61dee7885be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/nav/div/ul[2]/li[2]/a/img</value>
      <webElementGuid>7ab396e1-8451-4072-8e13-218443d9fb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user-img']</value>
      <webElementGuid>834a4eb5-d95e-44c3-a441-1ef3c6177514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a/img</value>
      <webElementGuid>5f482691-0b10-418b-8a4d-8094049dd8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://asset.kgnewsroom.com/users/photo-8.jpg' and @alt = 'user-img']</value>
      <webElementGuid>598d892b-5cd1-4ec4-873e-1e3bd9a7d7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
